### PR TITLE
Implement ElevenLabs TTS

### PR DESCRIPTION
**Pull request by 3choff**
ElevenLabs Text-to-Speech (TTS) Integration:

- The voice assistant can now use the ElevenLabs TTS service for generating speech.
- The voice ID for the ElevenLabs TTS service is set to "Paul J.", which closely resembles Jarvis's voice.
- The output format is "mp3_22050_32" to ensure compatibility with the Free Tier of ElevenLabs's account.
- The model "eleven_turbo_v2" provides a good balance of speed and audio quality.
- The README has been updated with instructions and a link to the voice.

### CODE REVIEW

**Comment by 3choff** [comment]
@PromtEngineer I just sent the PR. The voice sounds very similar to me. Let me know if any changes are required

**Comment by PromtEngineer** [comment]
@3choff I will have a look. thanks for another amazing contribution.

**Comment by PromtEngineer** [comment]
@3choff can you please update the example.env file with ELEVAN_LABS_API. This looks great.

**Comment by 3choff** [comment]
@PromtEngineer Thanks, I updated the example.env

**Pull request merged**
